# Generated by Django 3.2.8 on 2021-10-17 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('directory', models.TextField()),
                ('branch_name', models.TextField()),
                ('default', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
