# Generated by Django 3.2.8 on 2021-10-18 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gitApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='autocommit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='autocommit_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
