# Generated by Django 3.2.8 on 2021-10-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitApp', '0002_auto_20211018_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('directory', models.TextField()),
                ('branch_name', models.TextField()),
            ],
        ),
    ]
